---
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"
    register: rg_output

  - name: Display resource group info
    debug:
      msg: "Resource group {{ rg_output.state.name }} created in {{ rg_output.state.location }}"

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ vnet_name }}"
      location: "{{ location }}"
      address_prefixes: "10.0.0.0/16"

  - name: Create subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ subnet_name }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ vnet_name }}"
      security_group:
        name: "{{ nsg_name }}"
        resource_group: "{{ resource_group }}"

  - name: Create Network Security Group
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ nsg_name }}"
      location: "{{ location }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
          source_address_prefix: "*"
        - name: HTTP
          protocol: Tcp
          destination_port_range: 80
          access: Allow
          priority: 1002
          direction: Inbound
          source_address_prefix: "*"
    register: nsg_output

  - name: Display NSG info
    debug:
      msg: 
        - "NSG {{ nsg_output.state.name }} created with rules:"
        - "SSH: Port 22 from {{ nsg_output.state.rules[0].source_address_prefix }}"
        - "HTTP: Port 80 from {{ nsg_output.state.rules[1].source_address_prefix }}"

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      name: "{{ vm_name }}-ip"
      location: "{{ location }}"
    register: public_ip_output

  - name: Display public IP info
    debug:
      msg: "Created public IP: {{ public_ip_output.state.ip_address }}"

  - name: Create network interface
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}-nic"
      location: "{{ location }}"
      create_with_security_group: false
      security_group: "{{ nsg_name }}"
      subnet_name: "{{ subnet_name }}"
      virtual_network: "{{ vnet_name }}"
      ip_configurations:
        - name: "ipconfig1"
          private_ip_allocation_method: "Dynamic"
          public_ip_allocation_method: "Static"
          public_ip_address_name: "{{ vm_name }}-ip"
          primary: true
    register: nic_output

  - name: Create Ubuntu VM
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      location: "{{ location }}"
      vm_size: Standard_B2als_v2
      admin_username: "{{ admin_username }}"
      ssh_password_enabled: false
      ssh_public_keys:
        - path: "/home/{{ admin_username }}/.ssh/authorized_keys"
          key_data: "{{ lookup('file', '~/.ssh/ansible_key.pub') }}"
      network_interfaces: "{{ vm_name }}-nic"
      image:
        offer: 0001-com-ubuntu-server-jammy
        publisher: Canonical
        sku: "22_04-lts-gen2"
        version: latest
      managed_disk_type: Standard_LRS 
      os_disk_caching: ReadWrite 
    register: vm_output